### ISSUE TITLE
Proposal: Null Finesse with a chop move

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#786] opened 2022-01-02 00:12 UTC
Generally, we never chop move cards that are not critical. So, I was thinking what if we do it in a null variant, specifically chop moving non critical null cards. 

Playfield: Null 1 is down
Cathy's hand: X - X - X - 5 - Null 3
Alice clue's 5 to Cathy
Bob can see that it's quite odd to chop move a null card that's not critical. Bob blind plays Null 2.
Cathy POV is that it's a 5 double pull. She blind plays null 3

**Comment by sjdrodge** [comment] 2022-01-02 00:40
Chop moving non-critical null cards seems like a valuable thing to do. Not something that is so strange it should call for a blind-play.

**Comment by Zamiell** [comment] 2022-01-02 00:41
> Chop moving non-critical null cards seems like a valuable thing to do. Not something that is so strange it should call for a blind-play.

https://hanabi.github.io/docs/variant-specific/null/#no-early-null-3-or-null-4-saves

**Comment by sjdrodge** [comment] 2022-01-02 00:44
Oh, gross. I guess I haven't played official Hyphen-ated null conventions in a while. In that case, I guess this makes sense as the conventions are currently configured.

**Comment by Zamiell** [comment] 2022-01-12 21:35
blocked by #589

**Comment by TheDaniMan** [comment] 2022-01-18 01:24
I'd rather see a more thorough rework of the null conventions, since I find the current ones very uncomfortable, and building on them in this specific way isn't going to help (still waiting on #589 either way though).

**Comment by Dr-Kakashi** [comment] 2022-01-19 14:03
> blocked by #589

How is it blocked by #589? 

>I'd rather see a more thorough rework of the null conventions, since I find the current ones very uncomfortable, and building on them in this specific way isn't going to help (still waiting on #589 either way though).

Let's do some null games and I'll show you the ropes. lol

**Comment by Zamiell** [comment] 2022-01-21 01:25
> How is it blocked by #589?

because it is my understanding that dawn is turned on for the whole game in null variants

**Comment by sjdrodge** [comment] 2022-01-21 01:30
> because it is my understanding that dawn is turned on for the whole game in null variants

This is not quite right, but when Dawn is on, the additional of a few extra conventions allows positional clues to be turned off completely.

**Comment by pianoblook** [comment] 2022-01-21 01:47
confirmed - Dawn is just extra-extra nice when playing non-positional Null, we've found

**Comment by mmelwen** [comment] 2022-01-23 06:20
I am totally on board with piano, I prefer to play null with normal conventions plus dawn plus re-clue 5 cm

**Comment by Zamiell** [comment] 2022-03-29 01:01
ok now that dawn is denied, does dani/mel have any thoughts on this issue?

**Comment by Zamiell** [comment] 2022-05-20 20:00
closing since this doesn't seem to have much support

**Closed by Zamiell** 2022-05-20 20:00 UTC
Labels: waiting-on-more-discussion
